config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}


 namespace :admin do

    resources :items, except: [:index]

    get '/' => 'homes#top'

    resources :users, only: [:index, :show, :edit, :update] do
      resources :reviews, only: [:index, :destroy]
    end



  end

  scope module: :public do

    resources :items, only: [:index, :show] do
      resources :reviews, only: [:index, :new, :create]
    end

    root to: 'homes#top'
    get 'about' => 'homes#about', as:'about'
    get 'search' => 'homes#search'

    resources :users, only: [:show, :edit, :update]
    get 'confirmation' => 'users#confirmation'
    patch 'withdrawal' => 'users#withdrawal'



  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :reviews, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true
  validates :kcal, presence: true
  validates :image, presence: true
  validates :protein, presence: true
  validates :fat, presence: true
  validates :carbohydrate, presence: true
  validates :protein_type, presence: true
  validates :price, presence: true
  validates :volume, presence: true
  validates :flavor, presence: true
  validates :brand, presence: true


  def self.search(params)

    if params[:item][:low_kcal].present? && params[:item][:high_kcal].present? && params[:item][:low_protein].present? && params[:item][:high_protein].present? && params[:item][:fat].present? && params[:item][:carbohydrate].present?
      @items = Item.where('kcal >= ? and kcal<= ? and protein >= ? and protein <= ? and fat <= ? and carbohydrate <= ?', params[:item][:low_kcal], params[:item][:high_kcal], params[:item][:low_protein], params[:item][:high_protein], params[:item][:fat], params[:item][:carbohydrate])

    elsif params[:item][:low_kcal].present? && params[:item][:high_kcal].present? && params[:item][:low_protein].present? && params[:item][:high_protein].present? && params[:item][:fat].present? && params[:item][:carbohydrate].blank?
      @items = Item.where('kcal >= ? and kcal<= ? and protein >= ? and protein <= ? and fat <= ?', params[:item][:low_kcal], params[:item][:high_kcal], params[:item][:low_protein], params[:item][:high_protein], params[:item][:fat])

    elsif params[:item][:low_kcal].present? && params[:item][:high_kcal].present? && params[:item][:low_protein].present? && params[:item][:high_protein].present? && params[:item][:fat].blank? && params[:item][:carbohydrate].present?
      @items = Item.where('kcal >= ? and kcal<= ? and protein >= ? and protein <= ? and carbohydrate <= ?', params[:item][:low_kcal], params[:item][:high_kcal], params[:item][:low_protein], params[:item][:high_protein], params[:item][:carbohydrate])

    elsif params[:item][:low_kcal].present? && params[:item][:high_kcal].present? && params[:item][:low_protein].present? && params[:item][:high_protein].blank? && params[:item][:fat].present? && params[:item][:carbohydrate].present?
      @items = Item.where('kcal >= ? and kcal<= ? and protein >= ? and fat <= ? and carbohydrate <= ?', params[:item][:low_kcal], params[:item][:high_kcal], params[:item][:low_protein], params[:item][:fat], params[:item][:carbohydrate])

    elsif params[:item][:low_kcal].present? && params[:item][:high_kcal].present? && params[:item][:low_protein].blank? && params[:item][:high_protein].present? && params[:item][:fat].present? && params[:item][:carbohydrate].present?
      @items = Item.where('kcal >= ? and kcal<= ? and protein <= ? and fat <= ? and carbohydrate <= ?', params[:item][:low_kcal], params[:item][:high_kcal], params[:item][:high_protein], params[:item][:fat], params[:item][:carbohydrate])

    elsif params[:item][:low_kcal].present? && params[:item][:high_kcal].blank? && params[:item][:low_protein].present? && params[:item][:high_protein].present? && params[:item][:fat].present? && params[:item][:carbohydrate].present?
      @items = Item.where('kcal >= ? and protein >= ? and protein <= ? and fat <= ? and carbohydrate <= ?', params[:item][:low_kcal], params[:item][:low_protein], params[:item][:high_protein], params[:item][:fat], params[:item][:carbohydrate])

    elsif params[:item][:low_kcal].blank? && params[:item][:high_kcal].present? && params[:item][:low_protein].present? && params[:item][:high_protein].present? && params[:item][:fat].present? && params[:item][:carbohydrate].present?
      @items = Item.where('kcal<= ? and protein >= ? and protein <= ? and fat <= ? and carbohydrate <= ?', params[:item][:high_kcal], params[:item][:low_protein], params[:item][:high_protein], params[:item][:fat], params[:item][:carbohydrate])

    elsif params[:item][:low_kcal].present? && params[:item][:high_kcal].present? && params[:item][:low_protein].present? && params[:item][:high_protein].present? && params[:item][:fat].blank? && params[:item][:carbohydrate].blank?
      @items = Item.where('kcal >= ? and kcal<= ? and protein >= ? and protein <= ?', params[:item][:low_kcal], params[:item][:high_kcal], params[:item][:low_protein], params[:item][:high_protein])

    elsif params[:item][:low_kcal].present? && params[:item][:high_kcal].present? && params[:item][:low_protein].present? && params[:item][:high_protein].blank? && params[:item][:fat].present? && params[:item][:carbohydrate].blank?
      @items = Item.where('kcal >= ? and kcal<= ? and protein >= ? and fat <= ?', params[:item][:low_kcal], params[:item][:high_kcal], params[:item][:low_protein], params[:item][:fat])

    elsif params[:item][:low_kcal].present? && params[:item][:high_kcal].present? && params[:item][:low_protein].blank? && params[:item][:high_protein].present? && params[:item][:fat].present? && params[:item][:carbohydrate].blank?
      @items = Item.where('kcal >= ? and kcal<= ? and protein <= ? and fat <= ?', params[:item][:low_kcal], params[:item][:high_kcal], params[:item][:high_protein], params[:item][:fat])

    elsif params[:item][:low_kcal].present? && params[:item][:high_kcal].blank? && params[:item][:low_protein].present? && params[:item][:high_protein].present? && params[:item][:fat].present? && params[:item][:carbohydrate].blank?
      @items = Item.where('kcal >= ? and protein >= ? and protein <= ? and fat <= ?', params[:item][:low_kcal], params[:item][:low_protein], params[:item][:high_protein], params[:item][:fat])

    elsif params[:item][:low_kcal].blank? && params[:item][:high_kcal].present? && params[:item][:low_protein].present? && params[:item][:high_protein].present? && params[:item][:fat].present? && params[:item][:carbohydrate].blank?
      @items = Item.where('kcal<= ? and protein >= ? and protein <= ? and fat <= ?', params[:item][:high_kcal], params[:item][:low_protein], params[:item][:high_protein], params[:item][:fat])

    elsif params[:item][:low_kcal].present? && params[:item][:high_kcal].present? && params[:item][:low_protein].present? && params[:item][:high_protein].blank? && params[:item][:fat].blank? && params[:item][:carbohydrate].present?
      @items = Item.where('kcal >= ? and kcal<= ? and protein >= ? and carbohydrate <= ?', params[:item][:low_kcal], params[:item][:high_kcal], params[:item][:low_protein], params[:item][:carbohydrate])

    elsif params[:item][:low_kcal].present? && params[:item][:high_kcal].present? && params[:item][:low_protein].blank? && params[:item][:high_protein].present? && params[:item][:fat].blank? && params[:item][:carbohydrate].present?
      @items = Item.where('kcal >= ? and kcal<= ? and protein <= ? and carbohydrate <= ?', params[:item][:low_kcal], params[:item][:high_kcal], params[:item][:high_protein], params[:item][:carbohydrate])

    elsif params[:item][:low_kcal].present? && params[:item][:high_kcal].blank? && params[:item][:low_protein].present? && params[:item][:high_protein].present? && params[:item][:fat].blank? && params[:item][:carbohydrate].present?
      @items = Item.where('kcal >= ? and protein >= ? and protein <= ? and carbohydrate <= ?', params[:item][:low_kcal], params[:item][:low_protein], params[:item][:high_protein], params[:item][:carbohydrate])

    elsif params[:item][:low_kcal].blank? && params[:item][:high_kcal].present? && params[:item][:low_protein].present? && params[:item][:high_protein].present? && params[:item][:fat].blank? && params[:item][:carbohydrate].present?
      @items = Item.where('kcal<= ? and protein >= ? and protein <= ? and carbohydrate <= ?', params[:item][:high_kcal], params[:item][:low_protein], params[:item][:high_protein], params[:item][:carbohydrate])

    elsif params[:item][:low_kcal].present? && params[:item][:high_kcal].present? && params[:item][:low_protein].blank? && params[:item][:high_protein].blank? && params[:item][:fat].present? && params[:item][:carbohydrate].present?
      @items = Item.where('kcal >= ? and kcal<= ? and fat <= ? and carbohydrate <= ?', params[:item][:low_kcal], params[:item][:high_kcal], params[:item][:fat], params[:item][:carbohydrate])

    elsif params[:item][:low_kcal].present? && params[:item][:high_kcal].blank? && params[:item][:low_protein].present? && params[:item][:high_protein].blank? && params[:item][:fat].present? && params[:item][:carbohydrate].present?
      @items = Item.where('kcal >= ? and protein >= ? and fat <= ? and carbohydrate <= ?', params[:item][:low_kcal], params[:item][:low_protein], params[:item][:fat], params[:item][:carbohydrate])

    elsif params[:item][:low_kcal].blank? && params[:item][:high_kcal].present? && params[:item][:low_protein].present? && params[:item][:high_protein].blank? && params[:item][:fat].present? && params[:item][:carbohydrate].present?
      @items = Item.where('kcal<= ? and protein >= ? and fat <= ? and carbohydrate <= ?',params[:item][:high_kcal], params[:item][:low_protein], params[:item][:fat], params[:item][:carbohydrate])

    elsif params[:item][:low_kcal].present? && params[:item][:high_kcal].blank? && params[:item][:low_protein].blank? && params[:item][:high_protein].present? && params[:item][:fat].present? && params[:item][:carbohydrate].present?
      @items = Item.where('kcal >= ? and protein <= ? and fat <= ? and carbohydrate <= ?', params[:item][:low_kcal], params[:item][:high_protein], params[:item][:fat], params[:item][:carbohydrate])

    elsif params[:item][:low_kcal].blank? && params[:item][:high_kcal].present? && params[:item][:low_protein].blank? && params[:item][:high_protein].present? && params[:item][:fat].present? && params[:item][:carbohydrate].present?
      @items = Item.where('kcal<= ? and protein <= ? and fat <= ? and carbohydrate <= ?', params[:item][:high_kcal], params[:item][:high_protein], params[:item][:fat], params[:item][:carbohydrate])

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save

      redirect_to admin_item_path(@item.id), notice: '登録に成功しました'
    else
      flash.now.notice = "登録に失敗しました"
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    if @item.save

      redirect_to admin_item_path(@item.id), notice: '登録に成功しました'
    else
      flash.now.notice = "登録に失敗しました"
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_path
  end


  private
  def item_params
    params.require(:item).permit(:name, :kcal, :protein, :fat, :carbohydrate, :brand, :flavor, :volume, :protein_type, :price, :image)
  end


end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">

  <% if flash[:notice] %>
   <div class="notice-red">
     <%= flash[:notice] %>
   </div>
  <% end %>

  <div class="edit-text">
   <h4>商品編集</h4>
  </div>

  <div class="row justify-content-md-center mt-3">
    <div class="col-6">
      <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>

       <table class="table table-borderless">
          <tbody>

            <tr>
             <td>
              <%= f.label :image, "商品画像" %>
             </td>
             <td>
             <%= f.file_field :image, accept: "image/*" %>
             </td>
            </tr>

            <tr>
             <td>
              <%= f.label :name, "商品名" %>
             </td>
             <td>
              <%= f.text_field :name %>
             </td>
            </tr>

            <tr>
             <td>
              <%= f.label :kcal, "カロリー" %>
             </td>
             <td>
              <%= f.text_field :kcal %>
             </td>
            </tr>

            <tr>
             <td>
              <%= f.label :protein, "プロテイン" %>
             </td>
             <td>
              <%= f.text_field :protein %>
             </td>
            </tr>


            <tr>
             <td>
              <%= f.label :fat, "脂質" %>
             </td>
             <td>
              <%= f.text_field :fat %>
             </td>
            </tr>

            <tr>
             <td>
              <%= f.label :carbohydrate, "炭水化物" %>
             </td>
             <td>
              <%= f.text_field :carbohydrate %>
             </td>
            </tr>

            <tr>
             <td>
              <%= f.label :brand, "ブランド" %>
             </td>
             <td>
              <%= f.text_field :brand %>
             </td>
            </td>

            <tr>
             <td>
              <%= f.label :flavor, "風味" %>
             </td>
             <td>
              <%= f.text_field :flavor %>
             </td>
            </tr>

            <tr>
             <td>
              <%= f.label :volume, "内容量" %>
             </td>
             <td>
              <%= f.text_field :volume %>
             </td>
            </tr>

            <tr>
             <td>
              <%= f.label :protein_type, "種類" %>
             </td>
             <td>
              <%= f.text_field :protein_type %>
             </td>
            </tr>

            <tr>
             <td>
              <%= f.label :price, "値段" %>
             </td>
             <td>
              <%= f.text_field :price %>
             </td>
            </tr>

          </tbody>
       </table>

       <div class="pr_100-submit">
   　　　　 <button type="submit" class="btn btn-primary">変更を保存</button>
       </div>
      <% end %>

    </div>
  </div>


  </div>

app/views/admin/items/new.html.erb
<div class="container">

  <% if flash[:notice] %>
   <div class="notice-red">
     <%= flash[:notice] %>
   </div>
  <% end %>
  
 <div class="edit-text">
  <h4>商品新規登録</h4>
 </div>

 <div class="row justify-content-md-center mt-3">
  <div class="col-6">
   <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>

    <table class="table table-borderless">
     <tbody>
      
      <tr>
       <td>
        <%= f.label :image, "商品画像" %>
       </td>
       <td>
        <%= f.file_field :image, accept: "image/*" %>
       </td>
      </tr>

      <tr>
       <td>
        <%= f.label :name, "商品名" %>
       </td>
       <td>
        <%= f.text_field :name %>
       </td>
      </tr>

      <tr>
       <td>
        <%= f.label :kcal, "カロリー" %>
       </td>
       <td>
        <%= f.text_field :kcal %>
       </td>
      </tr>

      <tr>
       <td>
        <%= f.label :protein, "たんぱく質量" %>
       </td>
       <td>
        <%= f.text_field :protein %>
       </td>
      </tr>

      <tr>
       <td>
        <%= f.label :fat, "脂質" %>
       </td>
       <td>
        <%= f.text_field :fat %>
       </td>
      </tr>

      <tr>
       <td>
        <%= f.label :carbohydrate, "炭水化物" %>
       </td>
       <td>
        <%= f.text_field :carbohydrate %>
       </td>
      </tr>

      <tr>
       <td>
        <%= f.label :brand, "ブランド" %>
       </td>
       <td>
        <%= f.text_field :brand %>
       </td>
      </tr>

      <tr>
       <td>
        <%= f.label :flavor, "風味" %>
       </td>
       <td>
        <%= f.text_field :flavor %>
       </td>
      </tr>

      <tr>
       <td>
        <%= f.label :volume, "内容量" %>
       </td>
       <td>
        <%= f.text_field :volume %>
       </td>
      </tr>

      <tr>
       <td>
        <%= f.label :protein_type, "種類" %>
       </td>
       <td>
        <%= f.text_field :protein_type %>
       </td>
      </tr>

      <tr>
       <td>
        <%= f.label :price, "金額" %>
       </td>
       <td>
        <%= f.text_field :price %>
       </td>
      </tr>
      
     </tbody>
    </table>  
      
  <div class="pr_100-submit">
   <button type ="submit" class="btn btn-primary">新規登録</button>
  </div>
  
 </div>
</div>

   <% end %>


</div>

app/views/admin/items/show.html.erb
<div class="container">

  <% if flash[:notice] %>
   <div class="notice-green">
     <%= flash[:notice] %>
   </div>
  <% end %>


  <h4>商品詳細</h4>

  <div class="row justify-content-md-center mt-3">
    <div class="col-3">
      <%= image_tag @item.image, size: "200x200" %>
    </div>
    <div class="col-9">
      <h5><%= @item.name %></h5>
      <table class="table">
        <tbody>
          <tr>
            <td>
              ブランド
            </td>
            <td>
              <%= @item.brand %>
            </td>
          </tr>
          <tr>
            <td>
              風味
            </td>
            <td>
              <%= @item.flavor %>味
            </td>
          </tr>
          <tr>
            <td>
              内容量
            </td>
            <td>
              <%= @item.volume %>g
            </td>
          </tr>
          <tr>
            <td>
              種類
            </td>
            <td>
              <%= @item.protein_type %>
            </td>
          </tr>
          <tr>
            <td>
              値段
            </td>
            <td>
              <%= @item.price %>円
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
    </div>
    <div class="col-9">
      <h5>一食当たり</h5>
        <table class="table">
          <tbody>
            <tr>
              <td>
                カロリー
              </td>
              <td>
                <%= @item.kcal %>
              </td>
              <td>
                たんぱく質
              </td>
              <td>
                <%= @item.protein %>
              </td>
            </tr>
            <tr>
              <td>
                脂質
              </td>
              <td>
                <%= @item.fat %>
              </td>
              <td>
                炭水化物
              </td>
              <td>
                <%= @item.carbohydrate %>
              </td>
            </tr>
          </tbody>
        </table>
    </div>
  </div>

  <div class="pt_50-link">
    <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>
  </div>
  <div class="pt_50-link">
     <%= link_to "削除する", admin_item_path(@item.id), method: :delete, data: {confirm: "本当に削除しますか？"}, class: 'btn btn-danger' %>
  </div>

</div>