config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}


 namespace :admin do

    resources :items, except: [:index]

    get '/' => 'homes#top'

    resources :users, only: [:index, :show, :edit, :update] do
      resources :reviews, only: [:index, :destroy]
    end



  end

  scope module: :public do

    resources :items, only: [:index, :show] do
      resources :reviews, only: [:index, :new, :create]
    end

    root to: 'homes#top'
    get 'about' => 'homes#about', as:'about'
    get 'search' => 'homes#search'

    resources :users, only: [:show, :edit, :update]
    get 'confirmation' => 'users#confirmation'
    patch 'withdrawal' => 'users#withdrawal'



  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
before_action :authenticate_admin!
  def top
    @items = Item.all.page(params[:page])
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">

  <div class="row justify-content-md-center mt-3">
   <div class="col-6">
     <div class="inline">
      <h4>商品一覧</h4>
     </div>
     <div class="inline-ml_325">
       <%= link_to "新規登録", new_admin_item_path, class:"btn btn-primary" %>
     </div>

     <% @items.each do |item| %>
    
      <table class="table">
        <tbody>
          <td>
            <%= image_tag item.image, size: "100x100" %>
          </td>
          <td>
            <%= link_to admin_item_path(item.id) do %>
             <%= item.name %>
            <% end %>
          </td>
        </tbody>
      </table>
  
     <% end %>
   
   </div>
  </div>


  <%= paginate @items, theme: 'bootstrap-5' %>


</div>