config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}


 namespace :admin do

    resources :items, except: [:index]

    get '/' => 'homes#top'

    resources :users, only: [:index, :show, :edit, :update] do
      resources :reviews, only: [:index, :destroy]
    end



  end

  scope module: :public do

    resources :items, only: [:index, :show] do
      resources :reviews, only: [:index, :new, :create]
    end

    root to: 'homes#top'
    get 'about' => 'homes#about', as:'about'
    get 'search' => 'homes#search'

    resources :users, only: [:show, :edit, :update]
    get 'confirmation' => 'users#confirmation'
    patch 'withdrawal' => 'users#withdrawal'



  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_one_attached :image

  validates :email, presence: true
  validates :name, presence: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
before_action :authenticate_admin!
  def index
    @users = User.all.page(params[:page]).per(8)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to admin_user_path(@user.id), notice: '変更に成功しました'
    else
      flash.now.notice = "変更に失敗しました"
      render :edit
    end
  end

  private
   def user_params
     params.require(:user).permit(:is_active)
   end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">

  <% if flash[:notice] %>
   <div class="notice-red">
     <%= flash[:notice] %>
   </div>
  <% end %>

  <div class="row justify-content-md-center mt-5">
   <div class="col-6">
  
    <h4><%= @user.name %> さんの会員情報編集</h4>
  
    <%= form_with model: @user, url: admin_user_path, method: :patch do |f| %>
  
    <table class="table table-borderless">
        <tbody>
          <tr>
            <td>
             会員ステータス
            </td>
            <td>
             <%= f.radio_button :is_active, "true", class:'ml-3' %>有効
             <%= f.radio_button :is_active, "false", class:'ml-5' %>無効
            </td>
          </tr>
        </tbody>
    </table>

    <div class="pr_100-submit">
     <%= f.submit '変更を保存', class: "btn btn-primary ml-5" %>
    </div>
    
    <% end %>
  
  </div>
 </div>


 
</div>

app/views/admin/users/index.html.erb
<div class="container">

  <h4>会員一覧</h4>

  <table class="table">
    <tr>
      <th class="table-secondary">会員ID</th>
      <th class="table-secondary">名前</th>
      <th class="table-secondary">メールアドレス</th>
      <th class="table-secondary">ステータス</th>
    </tr>
   <% @users.each do |user| %>
    <tbody>
      <tr>
        <td>
          <%= user.id %>
        </td>
        <td>
          <%= link_to admin_user_path(user.id) do %>
           <%= user.name %>
          <% end %>
        </td>
        <td>
          <%= user.email %>
        </td>
        <td>
          <% if user.is_active == true %>
           有効
          <% else %>
           無効
          <% end %>
        </td>
      </tr>
    </tbody>
   <% end %>
  </table>
  
  <%= paginate @users, theme: 'bootstrap-5' %>

</div>

app/views/admin/users/show.html.erb
<div class="container">

  <% if flash[:notice] %>
   <div class="notice-green">
     <%= flash[:notice] %>
   </div>
  <% end %>

  <div class="row justify-content-md-center mt-3">
    <div class="col-6">
     <h4><%= @user.name %>さんの会員詳細</h4>

      <table class="table table-borderless">
        <tbody>
          <tr>
            <td style="width: 40%">
              会員ID
            </td>
            <td>
              <%= @user.id %>
            </td>
          </tr>
          <tr>
            <td>
              <p class="mt-4">
               ユーザー画像
              </p>
            </td>
            <td>
              <% if @user.image.attached? %>
               <%= image_tag @user.image, size: "100x100" %>
              <% else %>
               <%= image_tag 'no_image.jpg', size: "100x100" %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td>
              名前
            </td>
            <td>
              <%= @user.name %>
            </td>
          </tr>
          <tr>
            <td>
              メールアドレス
            </td>
            <td>
              <%= @user.email %>
            </td>
          </tr>
          <tr>
            <td>
              会員ステータス
            </td>
            <td>
              <% if @user.is_active == true %>
               有効
              <% else %>
               無効
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>

    </div>
  </div>

 <div class="pr_200-submit">
  <%= link_to "編集する", edit_admin_user_path(@user.id), class: "btn btn-primary" %>
  <%= link_to "レビュー一覧", admin_user_reviews_path(@user.id), class: "btn btn-primary" %>
 </div>

</div>