config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}


 namespace :admin do

    resources :items, except: [:index]

    get '/' => 'homes#top'

    resources :users, only: [:index, :show, :edit, :update] do
      resources :reviews, only: [:index, :destroy]
    end



  end

  scope module: :public do

    resources :items, only: [:index, :show] do
      resources :reviews, only: [:index, :new, :create]
    end

    root to: 'homes#top'
    get 'about' => 'homes#about', as:'about'
    get 'search' => 'homes#search'

    resources :users, only: [:show, :edit, :update]
    get 'confirmation' => 'users#confirmation'
    patch 'withdrawal' => 'users#withdrawal'



  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProteinMania</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

     <% if admin_signed_in? %>

      <nav class="navbar navbar-light bg-light p-5">
       <form class="container-fluid justify-content-end">
        <button class="btn btn-sm btn-outline-secondary mr-auto" type="button">
          <%= link_to "プロテインマニア", admin_path %>
        </button>
        <button class="btn btn-sm btn-outline-secondary ml-5" type="button">
          <%= link_to "商品一覧", admin_path %>
        </button>
        <button class="btn btn-sm btn-outline-secondary ml-5" type="button">
          <%= link_to "会員一覧", admin_users_path %>
        </button>
        <button class="btn btn-sm btn-outline-secondary ml-5" type="button">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
        </button>
       </form>
      </nav>

     <% elsif user_signed_in? %>

      <nav class="navbar navbar-light bg-light p-5">
        <form class="container-fluid justify-content-end">
          <button class="btn btn-sm btn-outline-secondary mr-auto" type="button">
            <%= link_to "プロテインマニア", root_path %>
          </button>
          <button class="btn btn-sm btn-outline-secondary ml-5" type="button">
            <%= link_to "About", about_path %>
          </button>
          <button class="btn btn-sm btn-outline-secondary ml-5" type="button">
            <%= link_to user_path(current_user) do %>
              <%= current_user.name %>さんのマイページ
            <% end %>
          </button>
          <button class="btn btn-sm btn-outline-secondary ml-5" type="button">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </button>
        </form>
      </nav>

     <% else %>

      <nav class="navbar navbar-light bg-light p-5">
        <form class="container-fluid justify-content-end">
          <button class="btn btn-sm btn-outline-secondary mr-auto" type="button">
            <%= link_to "プロテインマニア", root_path %>
          </button>
          <button class="btn btn-sm btn-outline-secondary ml-5" type="button">
            <%= link_to "About", about_path %>
          </button>
          <button class="btn btn-sm btn-outline-secondary ml-5" type="button">
            <%= link_to "新規登録", new_user_registration_path %>
          </button>
          <button class="btn btn-sm btn-outline-secondary ml-5" type="button">
            <%= link_to "ログイン", new_user_session_path %>
          </button>
        </form>
      </nav>

     <% end %>

    </header>



     <%= yield %>
  </body>
</html>